import { useEffect, useRef, useState } from 'react'
import { cheatsheet, categories, filterCheats, builderFields, buildPrompt, categoryDescriptions, groupCheats } from '../../data/aiGuide/cheatsheets/prompting'
import CopyButton from './cheatsheets/CopyButton'
import CheatsheetAccordion, { AccordionControls, useCheatsheetAccordions } from './cheatsheets/CheatsheetAccordion'
import CheatsheetSearch from './cheatsheets/CheatsheetSearch'
import './cheatsheet.css'
import './cheatsheets/cheatsheets.css'
function CheatRow({item}){return <article tabIndex={-1} id={'prompt-'+item.id} className={'prompt-item'+(item.category==='Prompt Recipes'?' prompt-recipe':'')}><header><h4>{item.shortcut}</h4><span className="prompt-category">{item.category}</span></header><p>{item.description}</p>{item.shortcut==='TCCA'&&<div className="tcca-labels"><span>TASK</span><span>CONTEXT</span><span>CONSTRAINTS</span><span>ASK</span></div>}<pre>{item.prompt}</pre><div className="prompt-tags">{item.tags.filter(tag=>tag!=='Code').map(tag=><span key={tag}>{tag}</span>)}</div><CopyButton text={item.prompt} label={item.template?'Copy template':'Copy'} name={item.shortcut}/>{item.example&&<details><summary>Example</summary><p>{item.example}</p></details>}</article>}
const placeholders={Role:'Experienced research software engineer',Goal:'Review this FastAPI endpoint',Context:'Biomedical research application',Constraints:'Do not change the API contract',Evidence:'Reference official documentation where necessary',Output:'Prioritised findings',Verification:'Check security, correctness and regressions'}
function PromptBuilder(){const [values,setValues]=useState({});const preview=buildPrompt(values);return <details className="prompt-builder"><summary>Build a Prompt <span>Combine only the context you need</span></summary><div className="builder-content"><div className="builder-fields">{builderFields.map(field=><label key={field}>{field}<textarea value={values[field]||''} placeholder={placeholders[field]} onChange={e=>setValues(v=>({...v,[field]:e.target.value}))}/></label>)}</div><div className="builder-preview"><h3>Prompt preview</h3><pre aria-label="Combined prompt preview">{preview||'Fill in one or more fields to build your prompt.'}</pre><CopyButton text={preview} label="Copy Prompt" name="from builder"/><button className="text-link" onClick={()=>setValues({...placeholders})}>Load example</button>{preview&&<button className="text-link" onClick={()=>setValues({})}>Clear fields</button>}</div></div></details>}
export default function PromptCheatsheet({initialPrompt} = {}){
 const [category,setCategory]=useState('All'),[query,setQuery]=useState('');const visible=filterCheats(cheatsheet,category,query);const reference=useRef(null);const pending=useRef(null)
 const groups=groupCheats(visible,category)
 const accordions=useCheatsheetAccordions(categories, query)
 useEffect(()=>{const header=document.querySelector('.site-header');if(!header)return;const update=()=>reference.current?.style.setProperty('--prompt-header-height',header.getBoundingClientRect().height+'px');update();const observer=new ResizeObserver(update);observer.observe(header);return()=>observer.disconnect()},[])
 useEffect(()=>{if(!pending.current)return;const target=document.getElementById(pending.current);if(target&&!target.closest('[hidden]')){pending.current=null;target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}},[category,query,accordions.open])
 const show=id=>{const item=cheatsheet.find(item=>item.id===id);if(!item)return;pending.current='prompt-'+id;setCategory('All');setQuery('');accordions.expand(item.category)}
 useEffect(()=>{if(initialPrompt)show(initialPrompt)},[initialPrompt])
 const changeCategory=c=>{setCategory(c);setQuery('');if(c!=='All')accordions.expand(c)}
 return <section ref={reference} className="prompt-reference" aria-labelledby="prompt-heading"><header><p className="eyebrow">Personal reference</p><h2 id="prompt-heading">Prompt & Agent Cheatsheet</h2><p>Practical patterns for prompting, research, coding and agent workflows.</p><p>Use one pattern when possible. Combine a few only when the task requires additional context, control or verification.</p><p className="prompt-notice">Prompt shortcuts are memorable natural-language patterns, not built-in AI commands unless explicitly marked otherwise.</p><p className="prompt-platforms">For use with ChatGPT, Claude, Gemini and coding agents. Adapt patterns to the tools and capabilities available in your workflow.</p></header>
 <nav className="prompt-categories" aria-label="Cheatsheet categories">{['All',...categories].map(c=><button key={c} type="button" aria-pressed={category===c} className={['Context & Clarification','Evidence & Verification'].includes(c)?'prompt-important':''} onClick={()=>changeCategory(c)}>{c}</button>)}</nav>
 <PromptBuilder/>
 <section className="prompt-featured" aria-label="Most useful prompts"><h3>Most useful</h3><div>{cheatsheet.filter(item=>item.featured).map(item=><button key={item.id} onClick={()=>show(item.id)}>{item.title}</button>)}</div></section>
 <details className="prompt-directory"><summary>Prompts at a glance</summary><div className="prompt-directory-grid">{groupCheats(cheatsheet).map(group=><section key={group.category}><h4>{group.category}</h4><ul>{group.items.map(item=><li key={item.id}><a href={'#/ai-lab/guide/cheatsheet/'+item.id} onClick={event=>{event.preventDefault();show(item.id)}}>{item.shortcut}</a></li>)}{group.category==='Learning'&&<li><a href="#/ai-lab/guide/cheatsheet/eli10" onClick={event=>{event.preventDefault();show('eli10')}}>ELI10</a></li>}</ul></section>)}</div></details>
 <CheatsheetSearch label="Search prompts, shortcuts and use cases..." value={query} onChange={value=>{setQuery(value);setCategory('All')}}/>
 {(query||category!=='All')&&<button className="button secondary" onClick={()=>{setCategory('All');setQuery('')}}>Clear filters</button>}
 <AccordionControls onExpand={accordions.expandAll} onCollapse={accordions.collapseAll}/>
 <p className="result-count" role="status">{visible.length} {visible.length===1?'pattern':'patterns'}{category!=='All'?' in '+category:''}</p>
 {visible.length?<div className="prompt-sections">{groups.map(group=><CheatsheetAccordion key={group.category} title={group.category} description={categoryDescriptions[group.category]} count={group.items.length} unit="patterns" open={accordions.isOpen(group.category)} onToggle={()=>accordions.toggle(group.category)}><div className="prompt-grid">{group.items.map(item=><CheatRow key={item.id} item={item}/>)}</div></CheatsheetAccordion>)}</div>:<div className="empty-state"><h3>No matching patterns</h3><p>Try a broader term or clear the category filter.</p></div>}
 <footer className="prompt-sources"><h3>Sources & inspiration</h3><p>This is a personal, organised reference. The linked collections offer additional inspiration; they are not the source of every pattern here.</p><a href="https://www.tminusai.com/cheatcodes" target="_blank" rel="noopener noreferrer">T-Minus AI — Prompt Cheat Codes ↗<span className="sr-only"> (opens in a new tab)</span></a><a href="https://www.sabrina.dev/t/prompts" target="_blank" rel="noopener noreferrer">Sabrina Ramonov — Prompt resources ↗<span className="sr-only"> (opens in a new tab)</span></a></footer>
 </section>
}
