import { publicationByLegacySlug } from '../data/research/projects'
import { UpdatesPreview } from '../components/aiGuide/AIUpdates'
import { useState } from 'react'
import SectionHeader from '../components/SectionHeader'
import { navigation } from '../data/navigation'
import { aiLabSections, leaderTrack } from '../data/aiLab/sections'
import { researchIdeas, researchIdeaBySlug } from '../data/aiLab/researchIdeas'
import { evaluations, evaluationBySlug, evaluationCategories, filterEvaluations } from '../data/aiLab/evaluations'
import { strategyTopics, strategyBySlug } from '../data/aiLab/strategyTopics'
import { strategyToolkit } from '../data/aiLab/strategyToolkit'
import { topicById, topicHref } from '../data/aiGuide/topics'
import { projectBySlug } from '../data/projects'
import '../components/aiGuide/guide.css'
import '../components/aiGuide/aiLab.css'
const href=path=>'#/'+path
export default function AILab({page}) {
 const [,area,slug]=page.split('/');const detail=area==='evaluations'?evaluationBySlug(slug):area==='strategy'?strategyBySlug(slug):area==='projects'?researchIdeaBySlug(slug):null
 const title=detail?.title || (area==='evaluations'?'Evaluation Lab':area==='strategy'?'AI Strategy & Leadership':area==='projects'?'AI Projects':'AI Lab')
 const copy=detail?.question||detail?.summary||(area==='evaluations'?'Reproducible experiments for understanding how models, agents and AI workflows perform in practice.':area==='strategy'?'Practical frameworks for choosing, governing, evaluating and scaling AI within organisations.':area==='projects'?aiLabSections[2].description:'A working space for learning, building, testing and thinking strategically about modern AI.')
 return <section className="page-section ai-lab-page"><SectionHeader as="h1" eyebrow={area==='evaluations'?'Testing AI systems':area==='strategy'?'AI Leadership':'AI Lab'} title={title} copy={copy}/><nav className="collection-links" aria-label="AI Lab sections">{navigation.find(group=>group.path==='ai-lab').items.map(([label,path])=><a key={path} href={href(path)} aria-current={page===path||page.startsWith(path+'/')&&path!=='ai-lab'?'page':undefined}>{label}</a>)}</nav>
 {detail?<><a className="text-link" href={href('ai-lab/'+area)}>← Back to {area==='strategy'?'AI Strategy':area==='evaluations'?'Evaluation Lab':'AI Projects'}</a>{area==='evaluations'?<EvaluationDetail item={detail}/>:area==='strategy'?<StrategyDetail item={detail}/>:<Idea item={detail}/>}</>:area==='evaluations'?<Evaluations/>:area==='strategy'?<Strategy/>:area==='projects'?<Ideas/>:<Overview/>}
 </section>
}
function Entry({title,description,path,status}){return <a className="lab-entry" href={href(path)}><p className="eyebrow">{status}</p><h3>{title}</h3><p>{description}</p><span className="text-link">View {status==='Evaluation'?'study':'topic'} →</span></a>}
function Overview(){return <><p className="lab-flow">Learn → Build → Explore → Evaluate → Lead</p><div className="guide-grid">{aiLabSections.map(section=><a className="lab-entry" href={href(section.path)} key={section.path}><p className="eyebrow">{section.purpose}</p><h2>{section.title}</h2><p>{section.description}</p><span className="text-link">{section.action} →</span></a>)}</div><section className="guide-group"><h2>Currently Exploring</h2><div className="guide-grid">{researchIdeas.filter(i=>i.featured).map(i=><Entry key={i.id} title={i.title} description={i.question} status="Idea" path={'ai-lab/projects/'+i.slug}/>)}{evaluations.filter(i=>i.featured).map(i=><Entry key={i.id} title={i.title} description={i.question} status="Evaluation" path={'ai-lab/evaluations/'+i.slug}/>)}{strategyTopics.filter(i=>i.featured).map(i=><Entry key={i.id} title={i.title} description={i.summary} status="Strategy" path={'ai-lab/strategy/'+i.slug}/>)}</div></section><UpdatesPreview/></>}
function Search({value,onChange,label}){return <label className="lab-search">{label}<input type="search" value={value} onChange={e=>onChange(e.target.value)} placeholder={label}/></label>}
function Idea({item}){return <article className="guide-card"><p className="eyebrow">{item.area} · {item.status}</p><h3>{item.title}</h3><dl className="lab-definition"><dt>Problem / opportunity</dt><dd>{item.question}</dd><dt>Why it matters</dt><dd>{item.whyItMatters}</dd><dt>Possible approach</dt><dd>{item.approach}</dd><dt>Technologies to explore</dt><dd>{item.technologies.join(' · ')}</dd><dt>Next step</dt><dd>{item.next}</dd></dl></article>}
function Ideas(){const [query,setQuery]=useState('');const items=researchIdeas.filter(i=>[i.title,i.area,i.question,i.approach,...i.technologies].join(' ').toLowerCase().includes(query.toLowerCase().trim()));return <><Search value={query} onChange={setQuery} label="Search AI projects"/><p role="status">{items.length} projects</p><div className="guide-grid">{items.map(item=><div key={item.id}><Idea item={item}/><a className="text-link" href={href('ai-lab/projects/'+item.slug)}>View project →</a></div>)}</div>{!items.length&&<p>No matching projects. Try a broader term.</p>}</>}
function Evaluations(){const [category,setCategory]=useState('All'),[query,setQuery]=useState('');const items=filterEvaluations(category,query);return <><p className="lab-note">Evaluations focus on measurable behaviour rather than model marketing claims. These are study plans; no results have been recorded.</p><div className="guide-filters" aria-label="Evaluation categories">{['All',...evaluationCategories].map(c=><button key={c} className="button secondary" aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><Search label="Search evaluations" value={query} onChange={setQuery}/><p role="status">{items.length} studies</p><div className="guide-grid">{items.map(item=><a className="lab-entry" key={item.id} href={href('ai-lab/evaluations/'+item.slug)}><p className="eyebrow">{item.category} · {item.status}</p><h2>{item.title}</h2><p>{item.question}</p><p className="guide-small">Measures: {item.measures.join(' · ')}</p><span className="text-link">View study →</span></a>)}</div>{!items.length&&<div className="empty-state"><h3>No matching studies</h3><button className="button secondary" onClick={()=>{setQuery('');setCategory('All')}}>Show all studies</button></div>}</>}
function EvaluationDetail({item}){return <><p className="eyebrow">{item.category} · {item.status}</p><div className="guide-grid">{[['Why this test',item.summary],['Systems to test',item.systems.join('; ')],['Test data — planned',item.testData],['Metrics',item.measures.join(' · ')],['Method — proposed',item.method],['Limitations',item.limitations],['Reproducibility',item.reproducibility]].map(([title,copy])=><section className="guide-card" key={title}><h2>{title}</h2><p>{copy}</p></section>)}</div>{item.results?<section className="guide-card"><h2>Results</h2><p>{item.results}</p></section>:<p className="lab-note">Evaluation planned. No results are available yet.</p>}<Related topics={item.relatedTopics} agents={item.relatedAgents} projects={item.relatedProjects}/></>}
function Related({topics=[],studies=[],agents=[],projects=[]}){return <section className="guide-group"><h2>Related</h2><ul>{topics.map(id=><li key={id}><a href={topicHref(id)}>AI Guide: {topicById(id).title} →</a></li>)}{studies.map(id=><li key={id}><a href={href('ai-lab/evaluations/'+id)}>Evaluation: {evaluationBySlug(id).title} →</a></li>)}{[...agents,...projects].map(id=>{const paper=publicationByLegacySlug(id);return <li key={id}><a href={paper?'#/research':href('work/'+id)}>{paper?.title||projectBySlug(id)?.title||'Research'} →</a></li>})}</ul></section>}
function Strategy(){return <><section className="guide-card caio-feature"><p className="eyebrow">Learning & leadership reference</p><h2>Chief AI Officer</h2><p>Connecting AI capability with strategy, governance, people and measurable organisational value.</p><p>This is an area of learning and strategic expertise I am developing, not a claim to hold a leadership position.</p><p className="lab-flow">Strategy · Portfolio · Governance · Technology · Adoption · Value</p><a className="text-link" href={href('ai-lab/strategy/chief-ai-officer')}>Explore the six areas →</a></section><div className="guide-grid">{strategyTopics.map(item=><Entry key={item.id} title={item.title} description={item.summary} status={item.status} path={'ai-lab/strategy/'+item.slug}/>)}</div><Toolkit/><section className="guide-group"><h2>AI Leader / CAIO learning track</h2><ol>{leaderTrack.map(([label,path])=><li key={label}><a href={href(path)}>{label}</a></li>)}</ol></section></>}
function Toolkit(){return <section className="guide-group"><h2>CAIO Toolkit</h2><div className="guide-grid">{strategyToolkit.map(item=><Entry key={item.title} title={item.title} description="Practical questions and frameworks to adapt to your organisation." status={item.status} path={'ai-lab/strategy/'+item.topic}/>)}</div></section>}
function StrategyDetail({item}){return <><p className="eyebrow">{item.status} · Learning reference</p><div className="guide-grid">{item.sections.map(([title,items])=><section className="guide-card" key={title}><h2>{title}</h2>{title==='Before deployment'?<div className="lab-checklist">{items.map(text=><label key={text}><input type="checkbox"/>{text}</label>)}</div>:<ul>{items.map(text=><li key={text}>{text}</li>)}</ul>}</section>)}</div>{item.id==='prioritisation'&&<><section className="guide-group"><h2>Impact / feasibility matrix</h2><div className="lab-matrix">{[['High impact / easy','Prioritise'],['High impact / difficult','Strategic investment'],['Low impact / easy','Opportunistic'],['Low impact / difficult','Avoid / defer']].map(([title,action])=><div key={title}><strong>{title}</strong><p>{action}</p></div>)}</div></section><Prioritiser/></>}<Related topics={item.relatedGuideTopics} studies={item.relatedEvaluations}/></>}
function Prioritiser(){const [scores,setScores]=useState({Impact:3,Feasibility:3,'Data readiness':3,'Strategic alignment':3,Risk:3,Cost:3});const indication=(scores.Impact+scores.Feasibility+scores['Data readiness']+scores['Strategic alignment']+(6-scores.Risk)+(6-scores.Cost))/6;return <section className="guide-card"><h2>Exploratory prioritisation aid</h2><p>Score each factor from 1–5. Higher risk and cost reduce the indication. This equal-weight discussion aid is not scientifically validated and cannot approve a project.</p><div className="lab-scores">{Object.entries(scores).map(([key,value])=><label key={key}>{key}: {value}<input type="range" min="1" max="5" value={value} onChange={e=>setScores(s=>({...s,[key]:Number(e.target.value)}))}/><meter min="1" max="5" value={value} aria-label={key+' score'}/></label>)}</div><p role="status"><strong>Priority indication: {indication.toFixed(1)} / 5 · {indication>=4?'Promising to investigate':indication>=2.5?'Needs further evidence':'Reconsider or defer'}</strong>{scores.Risk>=4?' High risk: resolve oversight and safeguards before proceeding.':''}</p><p className="guide-small">Method: average the four benefit/readiness scores with reversed risk and cost (6 − score). Time to value and non-negotiable constraints need separate review.</p></section>}
