import { useState } from 'react'
import SectionHeader from '../components/SectionHeader'
import ArtGallery from '../apps/geometry-art/components/ArtGallery'
import Games from '../apps/games/Games'
import GeneratedArt from '../components/creativeLab/GeneratedArt'
import { creativeSections, creativeStudy } from '../data/creativeLab'
import '../components/creativeLab/creativeLab.css'
export default function CreativeLab({page}) {
 const [,section,slug]=page.split('/');const category=creativeSections.find(s=>s.slug===section);const study=creativeStudy(section,slug)
 return <section className="page-section creative-lab"><SectionHeader as="h1" eyebrow="Creative Lab" title={study?.title||category?.title||'Creative Lab'} copy={study?.description||category?.intro||'A space for geometry, generative systems, data-inspired art, games and creative coding experiments.'}/><nav className="collection-links" aria-label="Creative Lab sections"><a href="#/creative-lab" aria-current={!section?'page':undefined}>Overview</a>{creativeSections.map(s=><a key={s.slug} href={'#/creative-lab/'+s.slug} aria-current={section===s.slug?'page':undefined}>{s.title}</a>)}</nav>
 {study?<Study key={study.id} item={study} section={section}/>:!category?<div className="creative-grid">{creativeSections.map((s,i)=><article className="creative-card" key={s.slug}><a href={'#/creative-lab/'+s.slug}><GeneratedArt kind={s.visual} seed={i+1} title={s.title+' generated preview'}/><div className="creative-caption"><h2>{s.title}</h2><p>{s.description}</p><span className="text-link">Explore →</span></div></a></article>)}</div>:section==='geometry'?<ArtGallery/>:section==='games'?<Games key={slug||'directory'} initialGame={slug}/>:<Gallery key={section} category={category}/>}
 </section>
}
function Gallery({category}){const [filter,setFilter]=useState('All');const items=category.items.filter(i=>filter==='All'||i.filters.includes(filter));return <>{category.slug==='data-art'&&<p className="feature-note">Generated and synthetic data only. These compositions explore what data can become visually; they do not represent scientific datasets or findings.</p>}<div className="creative-filters" aria-label="Filter studies">{category.filters.map(f=><button key={f} className="button secondary" aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><p role="status" className="result-count">{items.length} studies</p><div className="creative-grid">{items.map((item)=><article className="creative-card" key={item.id}><a href={'#/creative-lab/'+category.slug+'/'+item.slug}><div className="creative-preview"><GeneratedArt kind={item.visual} title={item.title}/><span className="creative-overlay">{item.title} · {item.category}<br/>View Study →</span></div><div className="creative-caption"><p className="eyebrow">{item.status}</p><h2>{item.title}</h2><p>{item.description}</p><div className="creative-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div><span className="text-link">View Study →</span></div></a></article>)}</div></>}
function Study({item,section}) {const [seed,setSeed]=useState(1),[amount,setAmount]=useState(50);return <><a className="text-link" href={'#/creative-lab/'+section}>← Back to {item.category}</a><figure className="creative-detail"><GeneratedArt kind={item.visual} seed={seed} amount={amount} title={item.title+' variation '+seed}/><figcaption>{item.synthetic?'Synthetic / algorithmically generated data. ':'Algorithmically generated study. '}Variation {seed} · {item.status}</figcaption></figure><div className="game-toolbar"><button className="button primary" onClick={()=>setSeed(s=>s+1)}>New Variation</button><label>Variation seed<input aria-label="Variation seed" type="number" min="1" max="999999" value={seed} onChange={e=>setSeed(Math.min(999999,Math.max(1,Number(e.target.value)||1)))}/></label><label>Composition <input type="range" min="10" max="90" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><output aria-live="polite">{amount}%</output></div><p>Adjust the composition or generate another variation. Reuse the same seed and composition to reproduce a study.</p><div className="creative-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div></>}
