import { useState } from 'react'
import SectionHeader from '../components/SectionHeader'
import { dataScienceCategories, dataScienceProjectBySlug, filterDataScienceProjects } from '../data/dataScience/projects'
import './dataScience.css'
export function DataScienceVisual({kind}) {
 const paths = {signal:'M10 70L30 70 40 30 50 105 60 55 80 70 100 70 110 20 120 110 130 60 150 70 170 70 180 35 190 100 200 65 230 70',survival:'M15 25H50V40H90V55H130V80H170V95H225',forecast:'M10 95Q30 35 50 70T90 65T130 55T170 45T220 25',causal:'M35 80L120 30 205 80M35 80H205',quality:'M20 95V55H55V35H90V65H125V20H160V45H195V80H225',spatial:'M50 25L110 15 150 40 200 30 220 75 175 110 120 95 75 115 30 70Z M110 15L120 95 M30 70L200 30 M75 115L150 40'}
 return <div className="ds-visual"><svg viewBox="0 0 240 130" aria-hidden="true"><path d={paths[kind] || paths.signal} fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"/><circle cx="120" cy="65" r="5" fill="currentColor"/></svg><span>Concept illustration</span></div>
}
export default function DataScience({page}) {
 const [category,setCategory] = useState('All')
 const project = dataScienceProjectBySlug(page.split('/')[1])
 if(project) return <section className="page-section ds-page"><a className="text-link" href="#/data-science">← Data Science Portfolio</a><SectionHeader as="h1" eyebrow={project.domain} title={project.title} copy={project.summary}/><p className="ds-status">{project.status}</p>{project.status!=='Completed'&&<p className="ds-plan-note">Project plan · Implementation and evaluation are not yet complete.</p>}<div className="ds-case-layout"><div>{[['Problem / Question',project.question],['Why it matters',project.whyItMatters],['Dataset',project.dataSource],['Exploratory analysis',project.exploratoryAnalysis],['Method',project.method],['Validation',project.validation],['Results',project.results],['Interactive visualisation',project.interactiveVisualisation],['Interpretation',project.interpretation],['Limitations',project.limitations],['Reproducibility',project.reproducibility]].filter(([,content])=>content).map(([title,content])=><section className="ds-case-section" key={title}><h2>{title}</h2><p>{content}</p></section>)}<section className="ds-case-section"><h2>Technologies</h2><p>{project.technologies.join(' · ')}</p></section>{(project.githubUrl||project.demoUrl)&&<section className="ds-case-section"><h2>Code / Demo</h2>{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noopener noreferrer">Code ↗</a>}{project.demoUrl&&<a href={project.demoUrl} target="_blank" rel="noopener noreferrer">Demo ↗</a>}</section>}</div><aside className="ds-demonstrates"><h2>What this demonstrates</h2>{project.status!=='Completed'&&<p>Planned capabilities</p>}<ul>{project.demonstrates.map(item=><li key={item}>{item}</li>)}</ul></aside></div></section>
 const items=filterDataScienceProjects(category)
 return <section className="page-section ds-page"><SectionHeader as="h1" eyebrow="Data & Analytics" title="Data Science Portfolio" copy="End-to-end data science projects spanning statistical modelling, machine learning, time series, data quality and interactive visualisation."/><div className="ds-filters" aria-label="Data Science categories">{dataScienceCategories.map(item=><button className="button secondary" key={item} aria-pressed={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</div><p role="status">{items.length} projects</p><div className="ds-grid">{items.map(item=><article className="ds-card" key={item.id}><DataScienceVisual kind={item.visual}/><div className="ds-card-body"><p className="eyebrow">{item.domain}</p><h2>{item.title}</h2><p>{item.summary}</p><span className="ds-status">{item.status}</span><dl><dt>Techniques</dt><dd>{item.methods.join(' · ')}</dd><dt>Potential technologies</dt><dd>{item.technologies.join(' · ')}</dd></dl><a className="text-link" href={'#/data-science/'+item.slug}>View project →</a></div></article>)}</div></section>
}
