import { leaderTrack } from '../data/aiLab/sections'
import { navigation } from '../data/navigation'
import { useState } from 'react'
import SectionHeader from '../components/SectionHeader'
import CheatsheetLanding from '../components/aiGuide/cheatsheets/CheatsheetLanding'
import { topics, topicGroups, learningTracks, topicById, topicHref, guideUpdated, guideSubtitle } from '../data/aiGuide/topics'
import { guideTools } from '../data/aiGuide/tools'
import { aiUpdates } from '../data/aiGuide/news'
import AIUpdates, { UpdateCard } from '../components/aiGuide/AIUpdates'
import { cheatsheet } from '../data/aiGuide/cheatsheet'
import '../components/aiGuide/guide.css'
export const guideTabs = ['Roadmap','Topics','Tools','AI Cheatsheets','AI Updates']
const guideTabId = tab => tab === 'AI Updates' ? 'news' : tab === 'AI Cheatsheets' ? 'cheatsheet' : tab.toLowerCase()
const guideHref = tab => '#/ai-lab/guide/'+guideTabId(tab)
const dateLabel = date => new Date(date+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})
function External({href,children}){return <a className="text-link" href={href} target="_blank" rel="noopener noreferrer">{children} ↗<span className="sr-only"> (opens in a new tab)</span></a>}
export default function Guide({page='ai-lab/guide'}) {
 const parts=page.split('/');const tab=parts[2]||'roadmap';const topic=tab==='topics'?topicById(parts[3]):null
 return <section className="page-section applied-guide"><nav className="guide-breadcrumb" aria-label="Breadcrumb"><a href="#/ai-lab">AI Lab</a><span aria-hidden="true"> → </span><a href="#/ai-lab/guide">AI Guide</a>{topic&&<><span aria-hidden="true"> → </span><span>{topic.title}</span></>}</nav><nav className="collection-links" aria-label="AI Lab sections">{navigation.find(group=>group.path==='ai-lab').items.map(([label,path])=><a key={path} href={'#/'+path} aria-current={path==='ai-lab/guide'?'page':undefined}>{label}</a>)}</nav><SectionHeader as="h1" eyebrow="AI Guide" title={tab==='cheatsheet'?'AI Cheatsheets':topic?.title||'Applied AI Guide 2026'} copy={tab==='cheatsheet'?'Compact references for prompting, models, agents, context, evaluation, protocols, security and AI strategy.':topic?.summary||guideSubtitle}/><p className="guide-status">Living guide · Last updated: <time dateTime={guideUpdated}>{dateLabel(guideUpdated)}</time></p><nav className="collection-links guide-tabs" aria-label="AI Guide sections">{guideTabs.map(label=><a key={label} href={guideHref(label)} aria-current={tab===guideTabId(label)?'page':undefined}>{label}</a>)}</nav>
 {topic?<Topic topic={topic}/>:tab==='topics'?<Topics/>:tab==='tools'?<Tools/>:tab==='cheatsheet'?<CheatsheetLanding sheetId={parts[3]}/>:tab==='news'?<AIUpdates/>:<Roadmap/>}
 </section>
}
function TopicCard({topic}){return <a className="guide-topic-card" href={topicHref(topic.id)}><span className="guide-stage">{String(topic.stage).padStart(2,'0')}</span><div><h3>{topic.title}</h3><p>{topic.summary}</p><span className="text-link">View topic →</span></div></a>}
function Roadmap(){return <><h2>Roadmap</h2><p>Start with the core concepts, then choose the track that fits your work. The stage numbers are a learning map, not a requirement to complete everything in order.</p><div className="guide-roadmap">{topics.map(topic=><TopicCard key={topic.id} topic={topic}/>)}</div><h2>Choose a learning track</h2><div className="guide-grid">{learningTracks.map(([name,ids])=><section className="guide-card" key={name}><h3>{name}</h3><ul>{ids.map(id=><li key={id}><a href={topicHref(id)}>{topicById(id).title}</a></li>)}</ul></section>)}<section className="guide-card"><h3>AI Leader / CAIO</h3><ol>{leaderTrack.map(([label,path])=><li key={label}><a href={'#/'+path}>{label}</a></li>)}</ol><a className="text-link" href="#/ai-lab/strategy">Explore AI Strategy →</a></section></div></>}
function Topics(){return <><h2>Topics</h2><p>A knowledge map of concepts to understand, with practical exercises and official resources attached to each topic.</p>{topicGroups.map(([group,ids])=><section className="guide-group" key={group}><h2>{group}</h2><div className="guide-grid">{ids.map(id=>{const topic=topicById(id);return <article className="guide-card" key={id}><TopicCard topic={topic}/><ul className="guide-concepts">{topic.concepts.map(concept=><li key={concept}><a href={topicHref(id)}>{concept}</a></li>)}</ul></article>})}</div></section>)}</>}
function Topic({topic}){const tools=guideTools.filter(tool=>tool.topics.includes(topic.id));const updates=aiUpdates.filter(update=>update.topics.includes(topic.id));return <><a className="text-link" href={guideHref('Topics')}>← All topics</a><section className="guide-group"><h2>Concepts to understand</h2><ul className="guide-concepts">{topic.concepts.map(concept=><li key={concept}>{concept}</li>)}</ul>{topic.id==='protocols'&&<p>MCP focuses on connecting applications to tools and context. A2A focuses on communication between agents. Study authentication, permissions and trust boundaries in both; emerging UI and other protocol extensions are advanced topics.</p>}</section><section className="guide-card"><h2>Try it in practice</h2><p>{topic.practice}</p></section><section className="guide-group"><h2>Related tools</h2><div className="guide-grid">{tools.map(tool=><ToolCard key={tool.id} tool={tool}/>)}</div></section><section className="guide-group"><h2>Related cheatsheet patterns</h2><div className="collection-links">{[...new Set(topic.cheats)].map(id=><a key={id} href={'#/ai-lab/guide/cheatsheet/'+id}>{cheatsheet.find(item=>item.id===id)?.shortcut}</a>)}</div></section><section className="guide-group"><h2>Official resources</h2><ul>{topic.resources.map(resource=><li key={resource.url}><External href={resource.url}>{resource.label}</External></li>)}</ul></section><section className="guide-group"><h2>Related news</h2>{updates.length?updates.map(update=><UpdateCard key={update.id} update={update}/>):<p>No updates curated for this topic yet. <a href={guideHref('News')}>Browse AI Updates →</a></p>}</section><a className="text-link" href={guideHref('Roadmap')}>Back to the learning roadmap →</a></>}
function ToolCard({tool}){return <article className="guide-card guide-tool"><p className="eyebrow">{tool.category}</p><h3>{tool.name}</h3><p>{tool.use}</p><External href={tool.url}>Official site / docs</External><p className="guide-small">Used in roadmap stages</p><ul>{tool.topics.map(id=><li key={id}><a href={topicHref(id)}>{String(topicById(id).stage).padStart(2,'0')} · {topicById(id).title}</a></li>)}</ul></article>}
function Tools(){const [filter,setFilter]=useState('All');const groups=[...new Set(guideTools.map(tool=>tool.category))];return <><h2>Tools</h2><p>Products, frameworks and software to explore. Follow official documentation for current availability and supported capabilities.</p><div className="guide-filters" aria-label="Tool categories">{['All',...groups].map(group=><button key={group} className="button secondary" aria-pressed={filter===group} onClick={()=>setFilter(group)}>{group}</button>)}</div>{groups.filter(group=>filter==='All'||group===filter).map(group=><section className="guide-group" key={group}><h2>{group}</h2><div className="guide-grid">{guideTools.filter(tool=>tool.category===group).map(tool=><ToolCard key={tool.id} tool={tool}/>)}</div></section>)}</>}
