export function GameHeader({title,description}) {return <header className="strategy-header"><h2>{title}</h2><p>{description}</p></header>}
export function DifficultySelector({value,onChange,disabled}) {return <label>Difficulty<select value={value} disabled={disabled} onChange={event=>onChange(event.target.value)}>{['Easy','Medium','Hard'].map(level=><option key={level}>{level}</option>)}</select></label>}
export function GameStatus({game}) {
 const message=game.winner?(game.winner===game.human?'You win':'Computer wins'):game.draw?'Draw':!game.state.started?'Choose your settings, then start a new game.':game.state.error?'The computer could not finish its turn. Retry or restart.':game.thinking?'Computer thinking...':'Your turn'
 return <p className={'strategy-status'+(game.over?' strategy-result':'')} role="status" aria-atomic="true">{message}</p>
}
export function GameControls({game}) {return <div className="game-toolbar strategy-controls">{!game.state.started?<button className="button primary" onClick={game.start}>New Game</button>:<><button className="button secondary" onClick={game.setup}>New Game</button><button className={'button '+(game.over?'primary':'secondary')} onClick={game.start}>{game.over?'Play again':'Restart'}</button></>}{game.state.error&&<button className="button primary" onClick={game.retry}>Retry computer turn</button>}</div>}
export function GameSettings({game,ticTacToe=false}) {return <><div className="game-toolbar strategy-settings"><DifficultySelector value={game.difficulty} onChange={game.setDifficulty} disabled={game.state.started}/>{ticTacToe?<label>Your piece<select value={game.human} disabled={game.state.started} onChange={event=>game.setHuman(Number(event.target.value))}><option value={1}>X — you go first</option><option value={2}>O — computer goes first</option></select></label>:<label>Who goes first?<select value={game.first} disabled={game.state.started} onChange={event=>game.setFirst(event.target.value)}><option value="human">You</option><option value="computer">Computer</option></select></label>}</div><p className="strategy-help">{game.difficulty==='Easy'?'Easy: random valid moves.':game.difficulty==='Medium'?'Medium: wins, blocks and positional play.':ticTacToe?'Hard: full search for optimal play.':'Hard: deeper search with centre control and future threats.'}{game.state.started?' Choose New Game to change settings.':''}</p>{ticTacToe?<p className="strategy-legend">You: <strong>{game.human===1?'X':'O'}</strong> · Computer: <strong>{game.computer===1?'X':'O'}</strong></p>:<p className="strategy-legend"><span className="strategy-swatch mint" aria-hidden="true"/> You: mint · <span className="strategy-swatch lavender" aria-hidden="true"/> Computer: lavender</p>}</>}
export function navigateBoard(event,index,columns,total) {
 const destination={ArrowLeft:(index+total-1)%total,ArrowRight:(index+1)%total,ArrowUp:(index+total-columns)%total,ArrowDown:(index+columns)%total,Home:0,End:total-1}[event.key]
 if(destination===undefined)return
 event.preventDefault();event.currentTarget.parentElement.children[destination]?.focus()
}
