import { ArtPuzzle, Sudoku } from './puzzles/PuzzleGames'
import FourInARow from './strategy/fourInARow/FourInARow'
import TicTacToe from './strategy/ticTacToe/TicTacToe'
import MemoryGame from './MemoryGame'
import { gameById, gameCategories, filterGames } from '../../data/creativeLab/games'
import { useEffect, useRef, useState } from 'react'
import { answerBank } from './words'
import { gradeWord, shapes, canPlace, canFit, placeBlock, slideTiles, spawnTile, hasMoves } from './logic'
import './games.css'
function GameCardContent({game,active}) {return <><span className="eyebrow">{game.category}</span><h2>{game.title}</h2><p>{game.description}</p>{game.difficulty&&<p className="game-difficulty">Difficulty: {game.difficulty}</p>}<span className="text-link">{active?'Playing':'Play →'}</span></>}
export default function Games({initialGame}) {
 const [active,setActive]=useState(initialGame || null)
 const [category,setCategory]=useState('All')
 const selected=gameById(active)
 return <div className="games-hub">{initialGame?<a className="text-link" href="#/creative-lab/games">← All games</a>:<><div className="creative-filters" aria-label="Game categories">{gameCategories.map(item=><button key={item} className="button secondary" aria-pressed={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</div><div className="game-catalogue">{filterGames(category).map(game=>(game.category==='Strategy'||game.id==='dot-mosaic'||game.id==='sudoku')?<a key={game.id} className="game-card game-card-link" href={'#/creative-lab/games/'+game.id}><GameCardContent game={game}/></a>:<button key={game.id} className={'game-card'+(active===game.id?' selected':'')} aria-pressed={active===game.id} onClick={()=>setActive(game.id)}><GameCardContent game={game} active={active===game.id}/></button>)}</div></>}{selected&&<section key={selected.id} className="game-panel" aria-label={selected.title}>{active==='letter-rush'?<LetterRush/>:active==='block-garden'?<BlockGarden/>:active==='double-trail'?<DoubleTrail/>:active==='four-in-a-row'?<FourInARow/>:active==='tic-tac-toe'?<TicTacToe/>:active==='dot-mosaic'?<ArtPuzzle/>:active==='sudoku'?<Sudoku/>:<MemoryGame/>}</section>}</div>
}
function LetterRush() {
  const [length,setLength]=useState(5), [limit,setLimit]=useState(90), [answer,setAnswer]=useState(''), [guesses,setGuesses]=useState([]), [entry,setEntry]=useState(''), [remaining,setRemaining]=useState(90), [status,setStatus]=useState('ready'), [message,setMessage]=useState('')
  const deadline=useRef(0), input=useRef(null)
  useEffect(()=>{if(status==='playing')input.current?.focus()},[status])
  useEffect(()=>{if(status!=='playing')return; const update=()=>{const seconds=Math.max(0,Math.ceil((deadline.current-Date.now())/1000));setRemaining(seconds);if(!seconds)setStatus('lost')};update();const timer=setInterval(update,200);return()=>clearInterval(timer)},[status])
  const start=()=>{const bank=answerBank(length);const word=bank[Math.floor(Math.random()*bank.length)];setAnswer(word);setGuesses([]);setEntry(word[0]);setMessage('');setRemaining(limit);deadline.current=Date.now()+limit*1000;setStatus('playing');input.current?.focus()}
  const submit=e=>{e.preventDefault();if(status!=='playing')return;if(Date.now()>=deadline.current){setRemaining(0);setStatus('lost');return}const guess=entry.toUpperCase();if(!new RegExp('^[A-Z]{'+length+'}$').test(guess)){setMessage('Enter exactly '+length+' letters.');return}if(guess[0]!==answer[0]){setMessage('Start with '+answer[0]+'.');return}if(guesses.includes(guess)){setMessage('Try a different guess.');return}const next=[...guesses,guess];setGuesses(next);setMessage('');setEntry(answer[0]);if(guess===answer)setStatus('won');else if(next.length===6)setStatus('lost')}
  return <><h2>Letter Rush</h2><p>Six guesses. The first letter is yours. Green = correct place; gold = elsewhere; grey = absent. Repeated letters are counted individually.</p><div className="game-toolbar"><label>Word length <select value={length} disabled={status==='playing'} onChange={e=>{setLength(Number(e.target.value));setStatus('ready');setAnswer('');setGuesses([]);setEntry('')}}>{[4,5,6,7].map(n=><option key={n} value={n}>{n} letters</option>)}</select></label><label>Round time <select value={limit} disabled={status==='playing'} onChange={e=>setLimit(Number(e.target.value))}>{[60,90,120].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></label><button className="button primary" onClick={start}>{status==='ready'?'Start round':'New round'}</button><strong role="timer" aria-label="Seconds remaining">{remaining}s</strong></div><p className="feature-note">Casual mode: alphabetic guesses are accepted without dictionary validation. The answers come from a built-in word bank.</p><div className="word-board" style={{'--letters':length}}>{Array.from({length:6},(_,r)=>{const guess=guesses[r];const grades=guess?gradeWord(answer,guess):[];return <div className="word-row" key={r}>{Array.from({length},(_,c)=><span key={c} className={'word-cell '+(grades[c]||'')} aria-label={guess ? guess[c]+': '+grades[c] : undefined}>{guess?.[c] || (r===guesses.length ? (c===0?answer[0]:entry[c]) : '')}</span>)}</div>})}</div><form onSubmit={submit} className="game-toolbar"><label>Your guess<input ref={input} value={entry} disabled={status!=='playing'} maxLength={length} autoComplete="off" autoCapitalize="characters" spellCheck={false} onChange={e=>setEntry(e.target.value.replace(/[^a-z]/gi,'').toUpperCase())}/></label><button className="button primary" disabled={status!=='playing'}>Guess</button></form><p role="status">{status==='won'?'Solved! The word was '+answer+'.':status==='lost'?'Round over. The word was '+answer+'.':message || (status==='ready'?'Choose your word length and start a round.':'Find the word before time runs out.')}</p></>
}
const deal=()=>Array.from({length:3},()=>shapes[Math.floor(Math.random()*shapes.length)])
function BlockGarden(){
 const [board,setBoard]=useState(Array(64).fill(0)),[tray,setTray]=useState(()=>deal()),[selected,setSelected]=useState(0),[score,setScore]=useState(0),[hover,setHover]=useState(null),[message,setMessage]=useState('')
 const over=tray.every(shape=>!shape||!canFit(board,shape));const shape=tray[selected];const preview=hover!==null&&shape&&canPlace(board,shape,Math.floor(hover/8),hover%8)?shape.map(([r,c])=>hover+r*8+c):[]
 const place=i=>{if(over||!shape)return;const result=placeBlock(board,shape,Math.floor(i/8),i%8);if(!result){setMessage('That shape does not fit here. Select another square or shape.');return}setBoard(result.board);setScore(s=>s+result.score);let next=tray.map((p,j)=>j===selected?null:p);if(next.every(p=>!p))next=deal();setTray(next);setSelected(next.findIndex(Boolean));setMessage('Placed. +'+result.score+' points.');setHover(null)}
 return <><h2>Block Garden</h2><p>Select a shape, then select its top-left position on the board. Complete rows or columns to clear them. Place all three shapes for a new set. Shapes cannot rotate.</p><div className="game-toolbar"><strong>Score: {score}</strong><button className="button secondary" onClick={()=>{setBoard(Array(64).fill(0));setTray(deal());setSelected(0);setScore(0);setMessage('');setHover(null)}}>New game</button></div><div className="block-board" onMouseLeave={()=>setHover(null)}>{board.map((value,i)=><button key={i} disabled={over} className={'block-cell'+(value?' filled':'')+(preview.includes(i)?' preview':'')} aria-label={'Row '+(Math.floor(i/8)+1)+', column '+(i%8+1)+(value?', occupied':', empty')} onFocus={()=>setHover(i)} onMouseEnter={()=>setHover(i)} onClick={()=>place(i)}/>)}</div><div className="block-tray" aria-label="Available shapes">{tray.map((p,i)=><button key={i} className={'shape-button'+(selected===i?' selected':'')} disabled={!p||over} aria-pressed={selected===i} aria-label={'Shape '+(i+1)+(p?': '+p.map(([r,c])=>'row '+(r+1)+' column '+(c+1)).join(', '):', used')} onClick={()=>{setSelected(i);setHover(null)}}>{p?<span className="shape-grid">{Array.from({length:16},(_,n)=><span key={n} className={p.some(([r,c])=>r===Math.floor(n/4)&&c===n%4)?'shape-dot':''}/>)}</span>:'Placed'}</button>)}</div><p role="status">{over?'No remaining shapes fit. Final score: '+score+'. Start a new game to try again.':message||'Choose a shape and make room for the next one.'}</p></>
}
const freshTiles=()=>spawnTile(spawnTile(Array(16).fill(0)))
function DoubleTrail(){
 const [game,setGame]=useState(()=>({board:freshTiles(),score:0})),[continued,setContinued]=useState(false);const touch=useRef(null);const won=game.board.some(v=>v>=2048),over=!hasMoves(game.board),locked=over||(won&&!continued)
 const move=direction=>{if(locked)return;setGame(previous=>{const result=slideTiles(previous.board,direction);return result.changed?{board:spawnTile(result.board),score:previous.score+result.score}:previous})}
 const keys={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down'}
 return <><h2>Double Trail</h2><p>Merge equal numbers to reach the 2048 tile. Each tile merges once per move. Use the direction buttons, swipe the board, or focus it and use arrow keys or WASD.</p><div className="game-toolbar"><strong>Score: {game.score}</strong><button className="button secondary" onClick={()=>{setGame({board:freshTiles(),score:0});setContinued(false)}}>New game</button></div><div className="number-board" tabIndex={0} role="group" aria-label="Number puzzle board. Use arrow keys to move tiles." onKeyDown={e=>{if(keys[e.key]){e.preventDefault();move(keys[e.key])}}} onTouchStart={e=>{touch.current=[e.touches[0].clientX,e.touches[0].clientY]}} onTouchCancel={()=>{touch.current=null}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current[0],dy=e.changedTouches[0].clientY-touch.current[1];touch.current=null;if(Math.max(Math.abs(dx),Math.abs(dy))>24)move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))}}>{game.board.map((v,i)=><div key={i} className={'number-tile'+(v?' occupied':'')} style={v?{background:'hsl('+Math.max(12,170-Math.log2(v)*13)+' 45% '+Math.max(29,85-Math.log2(v)*5)+'%)',color:v>=32?'white':'#10231f'}:{}} aria-label={'Row '+(Math.floor(i/4)+1)+', column '+(i%4+1)+': '+(v||'empty')}>{v||''}</div>)}</div><div className="direction-pad">{[['up','↑'],['left','←'],['down','↓'],['right','→']].map(([direction,label])=><button className="button secondary" key={direction} aria-label={'Move '+direction} disabled={locked} onClick={()=>move(direction)}>{label}</button>)}</div><p role="status">{over?'No moves left. Final score: '+game.score+'.':won&&!continued?'You reached 2048! Keep going or start again.':'Combine matching tiles and leave space to move.'}</p>{won&&!continued&&!over&&<button className="button primary" onClick={()=>setContinued(true)}>Keep playing</button>}</>
}
