import { useEffect, useState } from 'react'
export const memorySymbols=['◯','△','□','◇','☆','⬡','＋','≋','●','▲','■','◆']
export function createMemoryDeck(pairs){const cards=Array.from({length:pairs*2},(_,id)=>({id,symbol:memorySymbols[id%pairs]}));for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
export default function MemoryGame(){
 const [pairs,setPairs]=useState(8),[deck,setDeck]=useState(()=>createMemoryDeck(8)),[open,setOpen]=useState([]),[matched,setMatched]=useState([]),[moves,setMoves]=useState(0)
 useEffect(()=>{if(open.length!==2)return;const same=deck[open[0]].symbol===deck[open[1]].symbol;const timer=setTimeout(()=>{if(same)setMatched(m=>[...m,...open]);setOpen([])},same?250:900);return()=>clearTimeout(timer)},[open,deck])
 const reset=(count=pairs)=>{setPairs(count);setDeck(createMemoryDeck(count));setOpen([]);setMatched([]);setMoves(0)}
 const flip=i=>{if(open.length===2||open.includes(i)||matched.includes(i))return;if(open.length===1)setMoves(n=>n+1);setOpen(o=>[...o,i])}
 return <><h2>Pattern Pairs</h2><p>Reveal two cards and find matching geometric symbols. Remember what you have seen and clear the board in as few turns as possible.</p><div className="game-toolbar"><label>Board size<select value={pairs} onChange={e=>reset(Number(e.target.value))}><option value={6}>6 pairs</option><option value={8}>8 pairs</option><option value={12}>12 pairs</option></select></label><button className="button secondary" onClick={()=>reset()}>New game</button><strong>Turns: {moves} · Pairs: {matched.length/2}/{pairs}</strong></div><div className="memory-board">{deck.map((card,i)=>{const shown=open.includes(i)||matched.includes(i);return <button key={card.id} className={'memory-card'+(shown?' revealed':'')+(matched.includes(i)?' matched':'')} aria-label={'Card '+(i+1)+(shown?': '+card.symbol:', hidden')+(matched.includes(i)?', matched':'')} aria-pressed={shown} aria-disabled={open.length===2||matched.includes(i)} onClick={()=>flip(i)}>{shown?card.symbol:'?'}</button>})}</div><p role="status">{matched.length===deck.length?'All pairs found in '+moves+' turns!':open.length===2?(deck[open[0]].symbol===deck[open[1]].symbol?'A match!':'Not a match. Remember these positions.'):'Choose two cards.'}</p></>
}
